### ISSUE TITLE
CLI freezes in shell mode when connecting using interactive password a with long value

### ISSUE THREAD

**Issue by sauroter** [hivemq/mqtt-cli#103]
## Expected behavior
Client connects with password set to a long value.

## Actual behavior
CLI becomes unresponsive and needs to be terminated with CTRL+C.

### Steps

````
$ mqtt sh
$ con -pw
Enter value for --password (The password for authentication): $
````
Enter long password, e.g. a JWT.

### Reproducer code
No code.
## Details

1.0.1
Picocli 4.0.4
JVM: 11.0.4 (AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.4+11)
OS: Mac OS X 10.15 x86_64

**Comment by gitseti** [comment]
Thanks @sauroter,

the bug is happening because the picocli interactive mode for password reading is using the `Console.readPassword()` function. This function seems to only support reading up to 1024 characters. If you copy-paste a string with more than 1024 characters the excess characters get truncated. The problem now is that the readPassword method cannot process the next char which would be the newLine character to confirm the password. You can verify this by deleting the last character in the interactive mode via backspace and then pressing Enter which should work.

## Suggested solution:

I think the best and more secure practice to read longer passwords should be to provide a functionality which let's me read the password from a file or via an environment variable as suggested in a [picocli example](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/interactive/PasswordDemo.java):

```java
    @Option(names = "--pw:file")
    File passwordFile;

    @Option(names = "--pw:env")
    String passwordEnvironmentVariable;

    @Option(names = "--pw", interactive = true, /* ... * /)
    String password;
```

What do you think of this solution or could it be that I'm missing something?

**Comment by sauroter** [comment]
Thanks for looking into this!

I like the solution with environment variables. But thats just my opinion :)
