### ISSUE TITLE
Support for username and password in config file

### ISSUE THREAD

**Issue by LtChaser** [hivemq/mqtt-cli#98]
## Problem or use case
When using the config file, we can configure host and port, but not username and password. When using shell or command line, these parameters have to always be passed on the command (either on the con command in shell, or on the sub command in command line).

## Preferred solution or suggestions
Allow for setting of mqtt.username and mqtt.password (and when latter is left out, ask via prompt of course) in the config file.

**Comment by ahelmbr** [comment]
Not sure if this make sense in general, as user name and password are optional parameters that must not be used. 
Also if you would like to work with several clients connected in parallel it makes no sense for me to have a default user name and password that is used in general.

**Comment by gitseti** [comment]
Thanks for the issue @LtChaser,

This is certainly something which I could take care of in the next release of the CLI.

There are use cases in which users may not need to provide a password.
For this reason I think leaving out the `mqtt.password` field is not an option, because it would also prompt for the password in this use case.

What do you think about reserving a keyword for prompting the password? 
Maybe something like `mqtt.prompt-password=true`?

As @ahelmbr pointed out, currently the config is used to overwrite parameters which are *required* for a command to work. 

Could you explain the necessity of your proposed issue a little more clearly, so that I can understand it better?

**Comment by hertfelder** [comment]
I second this feature request since we have a similar situation. We are using the RBAC plugin and all clients are using the same username/password combination.

We would further need to also be able to set the `--cert` option via config file. Any chance this will be implemented?

**Comment by ahelmbr** [comment]
I think this using same client certificates is a pattern that is often the case, so that we will take your request adding the  certification properties to default settings 
as a new feature request in the next version.

**Comment by hertfelder** [comment]
Sounds great, thank you!

**Comment by deen13** [comment]
Has the originally requested feature been implemented? I came across this issue before reading the manual and noticed the `auth.username` and `auth.password` options which didn't worked for me.  

https://hivemq.github.io/mqtt-cli/docs/07_configuration.html
